load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "analysis",
    srcs = ["analysis.cc"],
    hdrs = ["analysis.h"],
    visibility = [
        "//src/flags:__pkg__",
        "//tests/flags/analysis:__pkg__",
    ],
)
