name: Release
on:
  push:
    tags:
    - v*
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - name: Install Bazelisk
      run: npm install -g @bazel/bazelisk
    - name: Test
      run: bazelisk test //...
  release:
    name: Release ${{ github.ref }}
    needs:
    - test
    runs-on: ubuntu-latest
    steps:
    - name: Create a release for ${{ github.ref }}
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        
        
        
       
